# Generated by Django 4.2.19 on 2025-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_genre_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Lenguaje')),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='Lenguage',
            field=models.ManyToManyField(blank=True, to='catalog.lenguage'),
        ),
    ]
