# Generated by Django 4.2.19 on 2025-03-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_lenguage_bookinstance_lenguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lenguaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.lenguage', verbose_name='Lenguaje original'),
        ),
    ]
