# Generated by Django 4.2.19 on 2025-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_lenguaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='foto',
            field=models.ImageField(null=True, upload_to='ImagenesEscritores'),
        ),
    ]
