# Generated by Django 4.2.19 on 2025-03-13 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_author_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='foto',
            field=models.ImageField(null=True, upload_to='ImagenesEscritores/'),
        ),
        migrations.CreateModel(
            name='UsuarioBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
