# Generated by Django 5.1.6 on 2025-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_author_foto_usuariobiblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobiblioteca',
            name='password',
            field=models.CharField(default='1234', max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='usuariobiblioteca',
            name='repetir',
            field=models.CharField(default='1234', max_length=100, verbose_name='Vuelve a introducir contraseña'),
        ),
    ]
