# Generated by Django 5.1.6 on 2025-03-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_usuariobiblioteca_password_usuariobiblioteca_repetir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobiblioteca',
            name='FechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
