# Generated by Django 5.1.6 on 2025-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_usuariobiblioteca_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
