# Generated by Django 5.1.6 on 2025-03-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_author_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='prestado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.usuariobiblioteca'),
        ),
    ]
