# Generated by Django 4.2.19 on 2025-03-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_bookinstance_prestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='portada',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
