# Generated by Django 4.2.19 on 2025-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_book_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='portada',
            field=models.URLField(blank=True, null=True),
        ),
    ]
