# Generated by Django 4.2.19 on 2025-03-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariobiblioteca',
            options={'permissions': (('can_mark_returned', 'marcar como devuelto'),)},
        ),
    ]
