# Generated by Django 5.1.6 on 2025-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_usuariobiblioteca_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ImagenesEscritores/'),
        ),
    ]
